### ISSUE TITLE
Hot water dispenser entity creation failure: device_state_attributes issue

### ISSUE THREAD

**Issue by joelmoses** [simbaja/ha_components#3]
The water_heater entity for the hot water dispenser on a GE refrigerator isn't created properly. It appears to be something incorrect in the device_state_attributes, resulting in:

- Inability to add entities to domain water_heater
- Resultant error in setting up ge_kitchen mapping for water_heater

Hopefully the error messages below are helpful.

```
2021-02-07 16:40:47 ERROR (MainThread) [homeassistant.components.water_heater] Error adding entities for domain water_heater with platform ge_kitchen
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 506, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 531, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 323, in _async_write_ha_state
attr.update(self.device_state_attributes or {})
File "/config/custom_components/ge_kitchen/entities/common/ge_water_heater.py", line 54, in device_state_attributes
return {**other_attrs}
TypeError: 'NoneType' object is not a mapping
2021-02-07 16:40:47 ERROR (MainThread) [homeassistant.components.water_heater] Error while setting up ge_kitchen platform for water_heater
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 206, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 506, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 531, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 323, in _async_write_ha_state
attr.update(self.device_state_attributes or {})
File "/config/custom_components/ge_kitchen/entities/common/ge_water_heater.py", line 54, in device_state_attributes
return {**other_attrs}
TypeError: 'NoneType' object is not a mapping
2021-02-07 16:41:17 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/ge_kitchen/update_coordinator.py", line 251, in on_device_update
entity.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 323, in _async_write_ha_state
attr.update(self.device_state_attributes or {})
File "/config/custom_components/ge_kitchen/entities/common/ge_water_heater.py", line 54, in device_state_attributes
return {**other_attrs}
TypeError: 'NoneType' object is not a mapping
2021-02-07 16:41:47 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/ge_kitchen/update_coordinator.py", line 251, in on_device_update
entity.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 323, in _async_write_ha_state
attr.update(self.device_state_attributes or {})
File "/config/custom_components/ge_kitchen/entities/common/ge_water_heater.py", line 54, in device_state_attributes
return {**other_attrs}
TypeError: 'NoneType' object is not a mapping
```

I'll continue to play with this (it looks like an object mismatch), but I need to learn the SDK first. :)

**Comment by joelmoses** [comment]
Correct me if I'm wrong, but it looks like there's no "return" in entities/fridge/ge_dispenser.py for the other_state_attrs property?

I think perhaps a "return data" after that section?

**Comment by joelmoses** [comment]
Yep, that was it. It's in my PR now.
